table registro_livros_marketing
	lineageTag: 566c611b-ec25-4fe2-99e2-6031c030fb5b

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 703011c7-b4ae-46a7-8256-d12c09f4e74b
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Título
		dataType: string
		lineageTag: 861c52fc-2d08-4f3e-8528-022eabff4b22
		summarizeBy: none
		sourceColumn: Título

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 45411460-3ba2-48d4-9069-2abb7ee47aec
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column 'Preço Unitário'
		dataType: decimal
		formatString: #,0.00
		lineageTag: 20778973-b1b9-4e06-88c3-2947a6f05031
		summarizeBy: none
		sourceColumn: Preço Unitário

		annotation SummarizationSetBy = Automatic

	column 'Preço Promocional'
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: afa17817-abac-4abf-921f-1b867f4a0c48
		summarizeBy: none
		sourceColumn: Preço Promocional

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Quantidade Vendas'
		dataType: int64
		formatString: 0
		lineageTag: d8ee3b11-574d-4993-aee7-d556d10feaf1
		summarizeBy: none
		sourceColumn: Quantidade Vendas

		annotation SummarizationSetBy = Automatic

	column Editora
		dataType: string
		lineageTag: 7e814949-48dd-4298-afbb-1b3c1b10f27c
		summarizeBy: none
		sourceColumn: Editora

		annotation SummarizationSetBy = Automatic

	partition registro_livros_marketing = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents(caminhoPasta & "registro_livros_marketing.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID", Int64.Type}, {"Preço Unitário", Currency.Type}, {"Preço Promocional", Currency.Type}, {"Quantidade Vendas", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

